### ISSUE TITLE
Should add the ability to access photos via file

### ISSUE THREAD

**Issue by carlylekatto** [SOME-1HING/google-reverse-image-api#2]
Add the ability to access photos through files for ease of use in many situations

**Comment by SOME-1HING** [comment]
@eienmojiki206 How about I add two parameters `picUrl` which is set to true, provides an array of image URL based on `limit` parameter? How does this sound?

**Comment by eienmojiki206** [comment]
> @eienmojiki206 How about I add two parameters `picUrl` which is set to true, provides an array of image URL based on `limit` parameter? How does this sound?

Oh, maybe it will be helpful, sound good.

**Comment by carlylekatto** [comment]
> @eienmojiki206 How about I add two parameters `picUrl` which is set to true, provides an array of image URL based on `limit` parameter? How does this sound?

@SOME-1HING Sounds good. But I strongly recommend editing the API so it can be more consistent. I'm assuming that the user wants to download an image from the Internet and then pass it into the API (Since the API doesn't always accept all image link formats), they might want to use the following code:
```javascript
const fs = require("fs");
const url = "https://google-reverse-image-api.vercel.app/reverse";

const data = new FormData()
const image = fs.createReadStream('/path/to/image')
data.append('image', image); // instead of "imageUrl"

fetch(url, {
  method: "POST",
  body: data,
})
  .then((response) => {
    if (response.ok) {
      return response.json();
    } else {
      throw new Error("Could not perform reverse image search.");
    }
  })
  .then((data) => console.log(data))
  .catch((error) => console.error(error));
```

**Comment by AryanPadmanabhan** [comment]
Has this been updated in the API? The ability to use a file of an image rather than a link. 

If so, how can I use it?

**Comment by SOME-1HING** [comment]
@AryanPadmanabhan I've been pretty busy lately, but I've still been trying to make some progress. However, I'm running into some problems when using the image buffer.

If anyone has any experience with this and can help me out, I'd really appreciate it!  Feel free to submit a pull request (PR) if you have a fix.

**Comment by Andarina** [comment]
#1 git_commit

**Comment by Andarina** [comment]
const fs = require("fs");
const url = "https://google-reverse-image-api.vercel.app/reverse";

const data = new FormData()
const image = fs.createReadStream('/path/to/image')
data.append('image', image); // instead of "imageUrl"

fetch(url, {
  method: "POST",
  body: data,
})
  .then((response) => {
    if (response.ok) {
      return response.json();
    } else {
      throw new Error("Could not perform reverse image search.");
    }
  })
  .then((data) => console.log(data))
  .catch((error) => console.error(error));
#1 git_commit

**Comment by Andarina** [comment]
git_commit
#3 error when access the end point

**Comment by Andarina** [comment]
> Add the ability to access photos through files for ease of use in many situations

git_commit
#1 creat_telegram_reverse

**Comment by SOME-1HING** [comment]
Sorry for the late reply, I will be adding the file upload search in future. For now, I am marking this issue as stale. You guys can use temporary image hosting services to get the image URL to reverse the image for now.
