### ISSUE TITLE
CORS error when accessing the endpoint from the browser

### ISSUE THREAD

**Issue by HovSyan** [SOME-1HING/google-reverse-image-api#3]
On a preflight call from the browser the OPTIONS call returns no CORS Allow headers, and as other applications runs in a different origin, the browser doesn't allow the api call to succeed. 

Can we handle this and add `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` headers to the OPTIONS call response.

I am not very good at Express and Node, but I guess it must be some sort of configurable option in the server config.

Thanks!

**Comment by Andarina** [comment]
Samhe I was in my account effect personal I enviros
#1
##2  

#2 git_commit

**Comment by SOME-1HING** [comment]
Thx @HovSyan for highlighting the issue and sorry for the late fix. I have fixed the CORS issue in the latest push, you can refer to commit 66465322434c22767b52a0ad8ea171f9ec735bbf for the changes made.
